pipeline {
    agent any
    stages {
        stage('checkout from scm') {
            steps {
                echo 'checkout..'
            }
        }
        stage('build') {
            steps {
                dir("web-ui"){
                    sh 'npm i'
                    sh 'npm run build'
                }
            }
        }
        stage('docker:build') {
            steps {
                dir("web-ui"){
                    sh 'docker build -t nagabhushanamn/web-ui .'
                }
            }
        }
        
    }
}