pipeline {
    agent any
    stages {
        stage('checkout from scm') {
            steps {
                echo 'checkout..'
            }
        }
        stage('build') {
            steps {
                dir("web-ui"){
                    sh 'npm run build'
                }
            }
        }
    }
}