pipeline {
    agent any
    stages {
        stage('checkout from scm') {
            steps {
                echo 'checkout..'
            }
        }
        stage('build') {
            steps {
                sh 'npm run build'
            }
        }
    }
}